name: Deploy to WordPress.org

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Composer install (no dev)
        run: composer install --no-dev --no-interaction --no-progress
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: ${{ github.event.repository.name }}
